# Generated by Django 4.2.7 on 2024-02-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Data_Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Series_reference', models.CharField(max_length=100)),
                ('Period', models.DecimalField(decimal_places=3, max_digits=15)),
                ('data_value', models.CharField(max_length=100, null=True)),
                ('suppresed', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('units', models.CharField(max_length=100)),
                ('magnitude', models.IntegerField()),
                ('subject', models.CharField(max_length=100, null=True)),
                ('group', models.CharField(max_length=100, null=True)),
                ('series_title_1', models.CharField(max_length=100, null=True)),
                ('series_title_2', models.CharField(max_length=100, null=True)),
                ('series_title_3', models.CharField(max_length=100, null=True)),
                ('series_title_4', models.CharField(max_length=100, null=True)),
                ('series_title_5', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
